histograms:
  "diff.*":
    nbins: 100
    min: -0.1
    max: 0.1

  diffz:
    nbins: 50
    min: -0.3
    max: 0.3

  "covXX|covYY":
    nbins: 100
    min: -0.0005
    max: 0.0005

  "covXY|covYX":
    nbins: 100
    min: -0.0001
    max: 0.0001

  "^n.*$":
    nbins: 50

  "truthX|truthY|recoX|recoY":
    min: -0.05
    max: 0.05

  "truthZ|recoZ":
    min: -200
    max: 200
    

extra_histograms:
  - expression: df["nRecoVtx"] / df["nTrueVtx"]
    name: "recoOverTrue"
    nbins: 50
  - expression: df["nRecoVtx"] / df["nVtxDetectorAcceptance"]
    name: "recoOverAcc"
    nbins: 50
  - expression: df["nRecoVtx"] / df["nVtxReconstructable"]
    name: "recoOverRecble"
    nbins: 50

